### ISSUE TITLE
False positives for `# rubocop:disable Metrics/BlockLength` (added in 0.44.0)

### ISSUE THREAD

**Issue by CaseyLeask** [codacy/codacy-rubocop#14]
Added in https://github.com/bbatsov/rubocop/releases/tag/v0.44.0 via https://github.com/bbatsov/rubocop/issues/3566, this now causes the line
``` ruby
# rubocop:disable Metrics/BlockLength
```
to give a false positive
```
Unnecessary disabling of `Metrics/BlockLength` (did you mean `Metrics/LineLength`?).
```

**Comment by pedrorijo91** [comment]
@rtfpessoa @machadoit can you have a look at this?

**Comment by rtfpessoa** [comment]
@CaseyLeask I am not sure I understand the problem. You want us to update Rubocop to the latest version 0.44.0?

**Comment by CaseyLeask** [comment]
@rtfpessoa In a nutshell, yes.

Rubocop 0.44.0 adds the linting rule `Metrics/BlockLength`. If this rule is disabled like this

``` ruby
# rubocop:disable Metrics/BlockLength
```

then `codacy-rubocop` reports this disabling as unnecessary, and reports this as a code quality issue.

**Comment by rtfpessoa** [comment]
@CaseyLeask ok, nice. I just did an update.

Next time you need to change the version feel free to send a PR. Usually helps to get it faster into production.

This should be released worse case in the next couple of days.
