### ISSUE TITLE
[CY-5550] Update Rubocop to 1.24.0+

### ISSUE THREAD

**Issue by mweitzel** [codacy/codacy-rubocop#286]
Can you bump the version to v1.24.0 or later? The v1.23.0 has huge conflicts with Ruby 3.1 syntax changes and rubocop -A for the latest versions.

Also, is there a standard schedule for when these versions are bumped? The cadence appears pretty erratic, so we're seeing frequent conflicts with our local versions and codacy's when using a tool like renovate to keep ourselves up to day.

**Comment by lolgab** [comment]
Rubocop is now updated to `1.25.0`. Thank you for letting us know @mweitzel
