### ISSUE TITLE
[CY-5967] Add support for Standard

### ISSUE THREAD

**Issue by dguettler** [codacy/codacy-rubocop#318]
Hello, 

please add support for https://github.com/testdouble/standard

Thank you,
Daniel

**Comment by stefanvacareanu7** [comment]
Hi there,

Thanks for reaching out to our community!

I am going to pass your proposal to the Product Team for further consideration.

Feel free to add any information about this topic and not only.

Best,
Stefan

**Comment by berniechiu** [comment]
Hmmm, is there any progress?
