### ISSUE TITLE
[CY-5991] Add support for rubocop-thread_safety

### ISSUE THREAD

**Issue by bmulholland** [codacy/codacy-rubocop#321]
https://github.com/covermymeds/rubocop-thread_safety

**Comment by stefanvacareanu7** [comment]
Hi there,

Thanks for reaching out to our community!

I am going to pass your proposal to the Engineering Team for further consideration.

Feel free to add any information about this topic and not only.

Best,
Stefan

**Comment by stefanvacareanu7** [comment]
Hi there,

Hope you're day is nice and sunny!

I just added the support for rubocop-thread_safety.

Best,
Stefan

**Comment by bmulholland** [comment]
Fantastic -- thank you!
