### ISSUE TITLE
Rubocop 0.54.0 release

### ISSUE THREAD

**Issue by vishthemenon** [codacy/codacy-rubocop#34]
Please could we make an update to rubocop 0.54.0?

**Comment by rtfpessoa** [comment]
Hi @vishthemenon due to breaking changes between Rubocop versions we are holding updates until we finish multi-version support.

I will create an internal task but this can take a bit.

**Comment by rtfpessoa** [comment]
At the moment there is not good way to do this.
For now you can avoid using patterns that have changed between versions while we implement a permanent solution.

**Comment by nicdal** [comment]
We have this issue:

Error: Unknown Ruby version 2.5 found in `.ruby-version`.
Supported versions: 2.1, 2.2, 2.3, 2.4

I guess it is related to missing updates too?

**Comment by rtfpessoa** [comment]
@nicdal I still do not have updates about this. At the moment we already have some scheduled updates but the permanent solution is still in the pipeline.

Will try to push this to the next iteration of the tool.

**Comment by rtfpessoa** [comment]
Rubocop was updated and already supports ruby 2.5. Sorry for the delay.
