### ISSUE TITLE
Add more rubocop rules.

### ISSUE THREAD

**Issue by MiguelSavignano** [codacy/codacy-rubocop#37]
Some rules are missing or other it's outdated or the example it's not the same with the rubocop doc info

example:
the example of Lint/AmbiguousOperator if diferent for
http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/AmbiguousOperator

**Comment by MiguelSavignano** [comment]
I try to generate updated info in this pull request https://github.com/codacy/codacy-rubocop/pull/38.

**Comment by MiguelSavignano** [comment]
The rubocop gem generates the documentation using the gem source code and yard gem.
I use this [code](https://github.com/MiguelSavignano/rubocop/blob/generate-doc-yml-file/lib/rubocop/docs/docs.rb) for generate rubocop-doc.yml.

This file contain all rubocop rules with examples with all the necessary information to generate codacy docs files. but the hard part is that the rubocop source code is necessary.

The ruby [script generator](https://github.com/MiguelSavignano/codacy-rubocop/blob/doc-generation-function/src/main/ruby/codacy/rubocop/generator.rb) use rucocop-doc.yml for generate makrdown, description.json and patters.json

**Comment by rtfpessoa** [comment]
This was fixed in the automatic doc generation a long time ago. Forgot to close this.
