### ISSUE TITLE
[CY-6594] Rubocop has not been updated

### ISSUE THREAD

**Issue by Covalent-DonR** [codacy/codacy-rubocop#400]
Hello, rubocop is still on 1.32.0 and 1.37.1 is the latest version. Could you please update rubocop and the other gems in this codacy worker?

Thank you

**Comment by stefanvacareanu7** [comment]
Hi there,

I bumped rubocop to use the latest version 1.38.0 in [this PR](https://github.com/codacy/codacy-rubocop/pull/402).

Hope this works nicely and smoothly for you.

Enjoy your weekend,
Stefan
